//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmManager.Resources.Strings.Sprachen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmManager.Resources.Strings.Sprachen.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu gesehen hinzufügen ähnelt.
        /// </summary>
        internal static string addToWatched {
            get {
                return ResourceManager.GetString("addToWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu Merkliste hinzufügen ähnelt.
        /// </summary>
        internal static string addToWatchlist {
            get {
                return ResourceManager.GetString("addToWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst zu Gesehen/Merkliste wechseln? ähnelt.
        /// </summary>
        internal static string askForNavigation {
            get {
                return ResourceManager.GetString("askForNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchschnittsbewertung ähnelt.
        /// </summary>
        internal static string averageVote {
            get {
                return ResourceManager.GetString("averageVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrund ähnelt.
        /// </summary>
        internal static string background {
            get {
                return ResourceManager.GetString("background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kann nicht zu Sammlung navigieren ähnelt.
        /// </summary>
        internal static string cantNavigateToCollection {
            get {
                return ResourceManager.GetString("cantNavigateToCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kann nicht zu Details navigieren ähnelt.
        /// </summary>
        internal static string cantNavigateToDetails {
            get {
                return ResourceManager.GetString("cantNavigateToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle Sprache ähnelt.
        /// </summary>
        internal static string chooseLanguage {
            get {
                return ResourceManager.GetString("chooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Wähle Theme ähnelt.
        /// </summary>
        internal static string chooseTheme {
            get {
                return ResourceManager.GetString("chooseTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liste löschen ähnelt.
        /// </summary>
        internal static string clearList {
            get {
                return ResourceManager.GetString("clearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sammlung ähnelt.
        /// </summary>
        internal static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Bewertungen ähnelt.
        /// </summary>
        internal static string countVote {
            get {
                return ResourceManager.GetString("countVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkles Theme ähnelt.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Detail ähnelt.
        /// </summary>
        internal static string details {
            get {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die existiert nicht ähnelt.
        /// </summary>
        internal static string doesNotExists {
            get {
                return ResourceManager.GetString("doesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigen ähnelt.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gib einen Schauspieler ein ähnelt.
        /// </summary>
        internal static string enterActor {
            get {
                return ResourceManager.GetString("enterActor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gib das Produzent Unternehmen ein ähnelt.
        /// </summary>
        internal static string enterCompany {
            get {
                return ResourceManager.GetString("enterCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Film ist bereits in der Liste enthalten ähnelt.
        /// </summary>
        internal static string enthaltenMovie {
            get {
                return ResourceManager.GetString("enthaltenMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Serie ist bereits in der Liste enthalten ähnelt.
        /// </summary>
        internal static string enthaltenSerie {
            get {
                return ResourceManager.GetString("enthaltenSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei ähnelt.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern/Laden ähnelt.
        /// </summary>
        internal static string filesOptions {
            get {
                return ResourceManager.GetString("filesOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string filterLanguage {
            get {
                return ResourceManager.GetString("filterLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für Erwachsene ähnelt.
        /// </summary>
        internal static string forAdults {
            get {
                return ResourceManager.GetString("forAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allgemeine Daten ähnelt.
        /// </summary>
        internal static string generalData {
            get {
                return ResourceManager.GetString("generalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinweis ähnelt.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich hinzugefügt ähnelt.
        /// </summary>
        internal static string insertSuccess {
            get {
                return ResourceManager.GetString("insertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache hat sich geändert und alles wurde neu geladen ähnelt.
        /// </summary>
        internal static string languageChanged {
            get {
                return ResourceManager.GetString("languageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Helles Theme ähnelt.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden ähnelt.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Daten laden ähnelt.
        /// </summary>
        internal static string loadData {
            get {
                return ResourceManager.GetString("loadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank laden ähnelt.
        /// </summary>
        internal static string loadDatabase {
            get {
                return ResourceManager.GetString("loadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geladen ähnelt.
        /// </summary>
        internal static string loaded {
            get {
                return ResourceManager.GetString("loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wird geladen ähnelt.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medien ähnelt.
        /// </summary>
        internal static string media {
            get {
                return ResourceManager.GetString("media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du Speichern oder Laden? ähnelt.
        /// </summary>
        internal static string messageFiles {
            get {
                return ResourceManager.GetString("messageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Film ähnelt.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filme ähnelt.
        /// </summary>
        internal static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Listen wurden erfolgreich geleert bzw. neu erstellt ähnelt.
        /// </summary>
        internal static string newGeneratedLists {
            get {
                return ResourceManager.GetString("newGeneratedLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu laden ähnelt.
        /// </summary>
        internal static string newLoad {
            get {
                return ResourceManager.GetString("newLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein erlaubter Typ  ähnelt.
        /// </summary>
        internal static string noAllowedType {
            get {
                return ResourceManager.GetString("noAllowedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast keinen gültigen Film gewählt! ähnelt.
        /// </summary>
        internal static string noChoosenMovie {
            get {
                return ResourceManager.GetString("noChoosenMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast keinen gültigen Film oder Serie gewählt! ähnelt.
        /// </summary>
        internal static string noChoosenMovieAndSerie {
            get {
                return ResourceManager.GetString("noChoosenMovieAndSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du hast keinen gültigen Serie gewählt! ähnelt.
        /// </summary>
        internal static string noChoosenSerie {
            get {
                return ResourceManager.GetString("noChoosenSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Sammlung vorhanden ähnelt.
        /// </summary>
        internal static string noCollection {
            get {
                return ResourceManager.GetString("noCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object ist null oder kein Object gewählt ähnelt.
        /// </summary>
        internal static string noObject {
            get {
                return ResourceManager.GetString("noObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Object (Film oder Serie) ist nicht in der Liste enthalten ähnelt.
        /// </summary>
        internal static string notIncludedObject {
            get {
                return ResourceManager.GetString("notIncludedObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Originalsprache ähnelt.
        /// </summary>
        internal static string originalLanguage {
            get {
                return ResourceManager.GetString("originalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Originaltitel ähnelt.
        /// </summary>
        internal static string originalTitle {
            get {
                return ResourceManager.GetString("originalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produzierland ähnelt.
        /// </summary>
        internal static string origionCountry {
            get {
                return ResourceManager.GetString("origionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Übersicht ähnelt.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berühmtheit ähnelt.
        /// </summary>
        internal static string popularity {
            get {
                return ResourceManager.GetString("popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frage ähnelt.
        /// </summary>
        internal static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erscheinungsdatum ähnelt.
        /// </summary>
        internal static string releaseDate {
            get {
                return ResourceManager.GetString("releaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gelöscht ähnelt.
        /// </summary>
        internal static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wurde gelöscht! ähnelt.
        /// </summary>
        internal static string removedMessage {
            get {
                return ResourceManager.GetString("removedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Von Liste entfernen ähnelt.
        /// </summary>
        internal static string removeFromList {
            get {
                return ResourceManager.GetString("removeFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank zurücksetzen ähnelt.
        /// </summary>
        internal static string resetDatabase {
            get {
                return ResourceManager.GetString("resetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abrufen ähnelt.
        /// </summary>
        internal static string retrieve {
            get {
                return ResourceManager.GetString("retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abgerufen ähnelt.
        /// </summary>
        internal static string retrieved {
            get {
                return ResourceManager.GetString("retrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeichert ähnelt.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern/Laden ähnelt.
        /// </summary>
        internal static string saveLoad {
            get {
                return ResourceManager.GetString("saveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gib eine Collection ein ähnelt.
        /// </summary>
        internal static string searchCollectionPlaceholder {
            get {
                return ResourceManager.GetString("searchCollectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Was willst du suchen? ähnelt.
        /// </summary>
        internal static string searchPlaceholder {
            get {
                return ResourceManager.GetString("searchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serien ähnelt.
        /// </summary>
        internal static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolg ähnelt.
        /// </summary>
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Serie wurde erfolgreich hinzugefügt ähnelt.
        /// </summary>
        internal static string successAddedMovie {
            get {
                return ResourceManager.GetString("successAddedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Film wurde erfolgreich hinzugefügt ähnelt.
        /// </summary>
        internal static string successAddedSerie {
            get {
                return ResourceManager.GetString("successAddedSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich ähnelt.
        /// </summary>
        internal static string successfully {
            get {
                return ResourceManager.GetString("successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle erfolgreich erstellt  ähnelt.
        /// </summary>
        internal static string successfullyCreatedTable {
            get {
                return ResourceManager.GetString("successfullyCreatedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich aus Gesehen entfernt ähnelt.
        /// </summary>
        internal static string successRemovedFromWatched {
            get {
                return ResourceManager.GetString("successRemovedFromWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich aus Merkliste entfernt ähnelt.
        /// </summary>
        internal static string successRemovedFromWatchlist {
            get {
                return ResourceManager.GetString("successRemovedFromWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Theme ähnelt.
        /// </summary>
        internal static string system {
            get {
                return ResourceManager.GetString("system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu der Sammlung des Films ähnelt.
        /// </summary>
        internal static string toCollection {
            get {
                return ResourceManager.GetString("toCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zum Inhalt der Sammlung ähnelt.
        /// </summary>
        internal static string toCollectionMembers {
            get {
                return ResourceManager.GetString("toCollectionMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu den Details ähnelt.
        /// </summary>
        internal static string toDetails {
            get {
                return ResourceManager.GetString("toDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bewertung ähnelt.
        /// </summary>
        internal static string vote {
            get {
                return ResourceManager.GetString("vote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesehen ähnelt.
        /// </summary>
        internal static string watched {
            get {
                return ResourceManager.GetString("watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesehen/Merkliste ähnelt.
        /// </summary>
        internal static string watchedWatchlist {
            get {
                return ResourceManager.GetString("watchedWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merkliste ähnelt.
        /// </summary>
        internal static string watchlist {
            get {
                return ResourceManager.GetString("watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merkliste und/oder Gesehen ähnelt.
        /// </summary>
        internal static string watchlistOrAndWatched {
            get {
                return ResourceManager.GetString("watchlistOrAndWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du Merkliste oder Gesehen anzeigen? ähnelt.
        /// </summary>
        internal static string whatDoYouWantToSee {
            get {
                return ResourceManager.GetString("whatDoYouWantToSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
