//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FilmManager.Resources.Strings.Sprachen {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FilmManager.Resources.Strings.Sprachen.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu gesehen hinzufügen ähnelt.
        /// </summary>
        internal static string addToWatched {
            get {
                return ResourceManager.GetString("addToWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu Merkliste hinzufügen ähnelt.
        /// </summary>
        internal static string addToWatchlist {
            get {
                return ResourceManager.GetString("addToWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die und ähnelt.
        /// </summary>
        internal static string and {
            get {
                return ResourceManager.GetString("and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Durchschnittsbewertung ähnelt.
        /// </summary>
        internal static string averageVote {
            get {
                return ResourceManager.GetString("averageVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergründe ähnelt.
        /// </summary>
        internal static string backdrops {
            get {
                return ResourceManager.GetString("backdrops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kann Wert nicht finden ähnelt.
        /// </summary>
        internal static string cantGetValue {
            get {
                return ResourceManager.GetString("cantGetValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kann nicht zu Details navigieren! ähnelt.
        /// </summary>
        internal static string cantNavigateToDetails {
            get {
                return ResourceManager.GetString("cantNavigateToDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        internal static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sammlung ähnelt.
        /// </summary>
        internal static string collection {
            get {
                return ResourceManager.GetString("collection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Bewertungen ähnelt.
        /// </summary>
        internal static string countVote {
            get {
                return ResourceManager.GetString("countVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produzenten ähnelt.
        /// </summary>
        internal static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dunkel ähnelt.
        /// </summary>
        internal static string dark {
            get {
                return ResourceManager.GetString("dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Du kannst keine Serie/Film als gesehen markieren, welche erst in der Zukunft erscheint.  ähnelt.
        /// </summary>
        internal static string dateIsFuture {
            get {
                return ResourceManager.GetString("dateIsFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beschreibung ähnelt.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  existiert nicht! ähnelt.
        /// </summary>
        internal static string doesNotExists {
            get {
                return ResourceManager.GetString("doesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du zur Cast Seite wechseln? ähnelt.
        /// </summary>
        internal static string doYouWantToNavigateToCast {
            get {
                return ResourceManager.GetString("doYouWantToNavigateToCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Englisch ähnelt.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Datei  ähnelt.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schreiben/Lesen ähnelt.
        /// </summary>
        internal static string filesOptions {
            get {
                return ResourceManager.GetString("filesOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Für Erwachsene ähnelt.
        /// </summary>
        internal static string forAdults {
            get {
                return ResourceManager.GetString("forAdults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deutsch ähnelt.
        /// </summary>
        internal static string german {
            get {
                return ResourceManager.GetString("german", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich hinzugefügt! ähnelt.
        /// </summary>
        internal static string insertSuccess {
            get {
                return ResourceManager.GetString("insertSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache wurde geändert! Es wird zu Start gewechselt.  ähnelt.
        /// </summary>
        internal static string languageChangedAndNavigateToHome {
            get {
                return ResourceManager.GetString("languageChangedAndNavigateToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hell ähnelt.
        /// </summary>
        internal static string light {
            get {
                return ResourceManager.GetString("light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Links zu Medien ähnelt.
        /// </summary>
        internal static string linksToMedia {
            get {
                return ResourceManager.GetString("linksToMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Laden ähnelt.
        /// </summary>
        internal static string load {
            get {
                return ResourceManager.GetString("load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geladen ähnelt.
        /// </summary>
        internal static string loaded {
            get {
                return ResourceManager.GetString("loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die wird geladen ähnelt.
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler beim Laden und öffnen ähnelt.
        /// </summary>
        internal static string loadingError {
            get {
                return ResourceManager.GetString("loadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als gesehen markieren ähnelt.
        /// </summary>
        internal static string markAsWatched {
            get {
                return ResourceManager.GetString("markAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Als gesehen markiert ähnelt.
        /// </summary>
        internal static string markedAsWatched {
            get {
                return ResourceManager.GetString("markedAsWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Willst du speichern oder laden? ähnelt.
        /// </summary>
        internal static string messageFiles {
            get {
                return ResourceManager.GetString("messageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Film ähnelt.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filme ähnelt.
        /// </summary>
        internal static string movies {
            get {
                return ResourceManager.GetString("movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank neu erstellt ähnelt.
        /// </summary>
        internal static string newGeneratedDatabase {
            get {
                return ResourceManager.GetString("newGeneratedDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nein ähnelt.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Kein gewählter Film oder Serie ähnelt.
        /// </summary>
        internal static string noChoosenMovieOrSerie {
            get {
                return ResourceManager.GetString("noChoosenMovieOrSerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Sammlung ähnelt.
        /// </summary>
        internal static string noCollection {
            get {
                return ResourceManager.GetString("noCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es wurde nichts gewählt! ähnelt.
        /// </summary>
        internal static string nothingSelectedMessage {
            get {
                return ResourceManager.GetString("nothingSelectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nichts gewählt ähnelt.
        /// </summary>
        internal static string nothingSelectedName {
            get {
                return ResourceManager.GetString("nothingSelectedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nicht entfernt! ähnelt.
        /// </summary>
        internal static string notRemoved {
            get {
                return ResourceManager.GetString("notRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Episoden ähnelt.
        /// </summary>
        internal static string numberOfEpisodes {
            get {
                return ResourceManager.GetString("numberOfEpisodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzahl Staffeln ähnelt.
        /// </summary>
        internal static string numberOfSeasons {
            get {
                return ResourceManager.GetString("numberOfSeasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Originalsprache ähnelt.
        /// </summary>
        internal static string originalLanguage {
            get {
                return ResourceManager.GetString("originalLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Original Titel ähnelt.
        /// </summary>
        internal static string originalTitle {
            get {
                return ResourceManager.GetString("originalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produzierland ähnelt.
        /// </summary>
        internal static string origionCountry {
            get {
                return ResourceManager.GetString("origionCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Überblick ähnelt.
        /// </summary>
        internal static string overview {
            get {
                return ResourceManager.GetString("overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seite ähnelt.
        /// </summary>
        internal static string page {
            get {
                return ResourceManager.GetString("page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Berühmtheit ähnelt.
        /// </summary>
        internal static string popularity {
            get {
                return ResourceManager.GetString("popularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Produktionsunternehmen ähnelt.
        /// </summary>
        internal static string productionCompanies {
            get {
                return ResourceManager.GetString("productionCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfehlungen ähnelt.
        /// </summary>
        internal static string recommendations {
            get {
                return ResourceManager.GetString("recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Veröffentlichungsdatum ähnelt.
        /// </summary>
        internal static string releaseDate {
            get {
                return ResourceManager.GetString("releaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernen ähnelt.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernt! ähnelt.
        /// </summary>
        internal static string removed {
            get {
                return ResourceManager.GetString("removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Datenbank zurücksetzen ähnelt.
        /// </summary>
        internal static string resetDatabase {
            get {
                return ResourceManager.GetString("resetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gespeichert ähnelt.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speichern/Laden ähnelt.
        /// </summary>
        internal static string saveLoad {
            get {
                return ResourceManager.GetString("saveLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche ähnelt.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suche Sammlung ähnelt.
        /// </summary>
        internal static string searchCollectionPlaceholder {
            get {
                return ResourceManager.GetString("searchCollectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Serien ähnelt.
        /// </summary>
        internal static string series {
            get {
                return ResourceManager.GetString("series", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zeige Popup ähnelt.
        /// </summary>
        internal static string showPopup {
            get {
                return ResourceManager.GetString("showPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erfolgreich ähnelt.
        /// </summary>
        internal static string successfully {
            get {
                return ResourceManager.GetString("successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tabelle erfolgreich erstellt! ähnelt.
        /// </summary>
        internal static string successfullyCreatedTable {
            get {
                return ResourceManager.GetString("successfullyCreatedTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zu den Details ähnelt.
        /// </summary>
        internal static string toDetails {
            get {
                return ResourceManager.GetString("toDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die da nur 500 Seiten abgerufen werden können, aber es mehr Seiten gab! ähnelt.
        /// </summary>
        internal static string tooMuchPages {
            get {
                return ResourceManager.GetString("tooMuchPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Typ ähnelt.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesehen ähnelt.
        /// </summary>
        internal static string watched {
            get {
                return ResourceManager.GetString("watched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gesehen/Merkliste ähnelt.
        /// </summary>
        internal static string watchedWatchlist {
            get {
                return ResourceManager.GetString("watchedWatchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Merkliste ähnelt.
        /// </summary>
        internal static string watchlist {
            get {
                return ResourceManager.GetString("watchlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ja ähnelt.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
