<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android</TargetFrameworks>
		<TargetFrameworks Condition="!$([MSBuild]::IsOSPlatform('linux'))">$(TargetFrameworks);</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net10.0-windows10.0.22000.0</TargetFrameworks>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->

		<OutputType>Exe</OutputType>
		<RootNamespace>FilmManager</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Enable XAML source generation for faster build times and improved performance.
				 This generates C# code from XAML at compile time instead of runtime inflation.
				 To disable, remove this line.
				 For individual files, you can override by setting Inflator metadata:
					 <MauiXaml Update="MyPage.xaml" Inflator="Default" /> (reverts to defaults: Runtime for Debug, XamlC for Release)
					 <MauiXaml Update="MyPage.xaml" Inflator="Runtime" /> (force runtime inflation) -->
		<MauiXamlInflator>SourceGen</MauiXamlInflator>

		<!-- Display name -->
		<ApplicationTitle>FilmManager</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.companyname.filmmanager</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<!-- To develop, package, and publish an app to the Microsoft Store, see: https://aka.ms/MauiTemplateUnpackaged -->
		<WindowsPackageType>None</WindowsPackageType>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<NeutralLanguage>de-AT</NeutralLanguage>
		<DefaultLanguage>de</DefaultLanguage>
		<GenerateSatelliteAssembliesForCore>true</GenerateSatelliteAssembliesForCore>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />
		
		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
	  <AndroidResource Remove=".github\**" />
	  <AndroidResource Remove="Geschrieben Dateien\**" />
	  <AndroidResource Remove="Resources\Icons\**" />
	  <Compile Remove=".github\**" />
	  <Compile Remove="Geschrieben Dateien\**" />
	  <Compile Remove="Resources\Icons\**" />
	  <EmbeddedResource Remove=".github\**" />
	  <EmbeddedResource Remove="Geschrieben Dateien\**" />
	  <EmbeddedResource Remove="Resources\Icons\**" />
	  <MauiCss Remove=".github\**" />
	  <MauiCss Remove="Geschrieben Dateien\**" />
	  <MauiCss Remove="Resources\Icons\**" />
	  <MauiXaml Remove=".github\**" />
	  <MauiXaml Remove="Geschrieben Dateien\**" />
	  <MauiXaml Remove="Resources\Icons\**" />
	  <None Remove=".github\**" />
	  <None Remove="Geschrieben Dateien\**" />
	  <None Remove="Resources\Icons\**" />
	</ItemGroup>

	<ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="Microsoft.Data.Sqlite.Core" Version="10.0.8" />
    <PackageReference Include="Microsoft.Maui.Controls" Version="10.0.70" />
    <PackageReference Include="CommunityToolkit.Maui" Version="14.1.1" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	  <PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.70" />
	  <PackageReference Include="OfficeIMO.Word" Version="1.0.59" />
	  <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
	  <PackageReference Include="TMDbLib" Version="3.0.0" />
	  <PackageReference Include="UraniumUI" Version="2.15.0" />
	  <PackageReference Include="UraniumUI.Material" Version="2.15.0" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\Strings\Sprachen\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Pages\SaveLoadPage.xaml.cs">
	    <DependentUpon>SaveLoadPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
    <MauiXaml Update="Pages\CollectionPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Pages\OverviewPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Pages\SettingPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
	  <MauiXaml Update="Pages\SaveLoadPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
    <MauiXaml Update="Pages\DetailPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Pages\MainPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Pages\WatchlistWatchedPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
    <MauiXaml Update="Pages\SearchPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Strings\Sprachen\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Views\OnClickPopup.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

</Project>
